
    env: 
        es6: true
        node: true

    extends: 
        - 'airbnb-base'
        - 'eslint:recommended'

    globals: 
        Atomics: readonly
        SharedArrayBuffer: readonly
    
    parserOptions:
        ecmaVersion: 2018
        sourceType: module
    
    parser: esprima

    plugins:
        - import
    rules:
        no-console: 0
        import/extensions: 0